### ISSUE TITLE
Run configuration

### ISSUE THREAD

**Issue by linsjb** [SIMS-2020/IDEP#54]
Konfigurationsfil för körning där diverse inställningar och beteende ställs in.
- Anomalier
- Sannolikhet att ett fel uppstår 
- Data typ (log/numeriska värden)
m.m.

### TODO
- [x] Read default config file from `configs` without flag
- [x] Read config file from `configs` with `--config` flag
- [x] Support for `json` and `yaml`
- [x] Convert file data tree to dot notation

**Comment by linsjb** [comment]
Close. tests left to do, issue #78.
